---
# Instructions:
# 1. Get access-token from VPSA, and paste here
# 2. Execute "kubectl create -f secrets.yaml", where secrets.yaml is this file
# 3. To verify: "kubectl -n kube-system get secrets", vpsa-access-token should appear
# 4. Remove this file, to keep your secrets safe
apiVersion: v1
kind: Secret
metadata:
  name: release-vpsa-access-token
  namespace: kube-system
  labels:
    app.kubernetes.io/name: zadara-csi
    app.kubernetes.io/instance: release
    app.kubernetes.io/version: "0.14.0"
    app: zadara-csi
    version: 0.14.0
    release: release
    stage: "production"
    publisher: "zadara"
    provisioner: csi.zadara.com
stringData:
  access-token: "1234ABCD5678EFGH-123"
---
