---
apiVersion: v1
name: zadara-csi
version: 0.5.1
appVersion: 0.14.1
description: "Container Storage Interface (CSI) driver for Zadara VPSA"
keywords: ["CSI", "Storage", "Zadara", "VPSA", "NAS", "Block", "Persistent Volume", "Cloud Storage", "STaaS", "PVC"]
home: zadara.com
icon: https://raw.githubusercontent.com/zadarastorage/zadara-csi/release-v0.14.0/helm/zadara-csi/icon.png
maintainers:
  - name: Lev Pechersky
    email: levp@zadara.com
